In [14]:
# Dependencies
import os
import matplotlib.cm as cm
import pandas as pd
import shutil
pd.options.mode.chained_assignment = None  # default='warn'

In [15]:

pop_path = os.path.join(".", "Resources/State/Demographic", "annual-est population_2010-2017.csv")
country_path = os.path.join(".", "Output/Demographic", "country_pop_2010-17.csv")
state_path = os.path.join(".", "Output/Demographic", "state_pop_2010-17.csv")

In [16]:
pop_data = pd.read_csv(pop_path, index_col=0, skiprows=3)
pop_data = pop_data.dropna(how='any') # drop any nan record
pop_data = pop_data.reset_index().rename(columns={"index": "State"})
pop_data["State"] = pop_data["State"].str.replace(".", "") 
pop_data = pop_data[:-1] #drop bottom 1 
country_data = pd.DataFrame(pop_data.iloc[0:5]).rename(columns={"State": "Region"})
country_data.to_csv(country_path)
country_data

,Region,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017
0,United States,"308,745,538","308,758,105","309,338,421","311,644,280","313,993,272","316,234,505","318,622,525","321,039,839","323,405,935","325,719,178"
1,Northeast,"55,317,240","55,318,350","55,388,349","55,642,659","55,860,261","56,047,732","56,203,078","56,296,628","56,359,360","56,470,581"
2,Midwest,"66,927,001","66,929,794","66,973,360","67,141,501","67,318,295","67,534,451","67,720,120","67,839,187","67,978,168","68,179,351"
3,South,"114,555,744","114,563,024","114,869,241","116,060,993","117,291,728","118,422,269","119,699,966","121,081,238","122,423,457","123,658,624"
4,West,"71,945,553","71,946,937","72,107,471","72,799,127","73,522,988","74,230,053","74,999,361","75,822,786","76,644,950","77,410,622"

In [17]:
pop_data = pop_data.drop(pop_data.index[[0,1,2,3,4]]).reset_index(drop=True)
pop_data.to_csv(state_path)
pop_data

,State,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017
0,Alabama,"4,779,736","4,780,135","4,785,579","4,798,649","4,813,946","4,827,660","4,840,037","4,850,858","4,860,545","4,874,747"
1,Alaska,"710,231","710,249","714,015","722,259","730,825","736,760","736,759","737,979","741,522","739,795"
2,Arizona,"6,392,017","6,392,309","6,407,002","6,465,488","6,544,211","6,616,124","6,706,435","6,802,262","6,908,642","7,016,270"
3,Arkansas,"2,915,918","2,916,031","2,921,737","2,938,640","2,949,208","2,956,780","2,964,800","2,975,626","2,988,231","3,004,279"
4,California,"37,253,956","37,254,518","37,327,690","37,672,654","38,019,006","38,347,383","38,701,278","39,032,444","39,296,476","39,536,653"
5,Colorado,"5,029,196","5,029,325","5,048,029","5,116,411","5,186,330","5,262,556","5,342,311","5,440,445","5,530,105","5,607,154"
6,Connecticut,"3,574,097","3,574,114","3,580,171","3,591,927","3,597,705","3,602,470","3,600,188","3,593,862","3,587,685","3,588,184"
7,Delaware,"897,934","897,936","899,712","907,884","916,868","925,114","934,805","944,107","952,698","961,939"
8,District of Columbia,"601,723","601,766","605,040","620,336","635,630","650,114","660,797","672,736","684,336","693,972"
9,Florida,"18,801,310","18,804,594","18,846,461","19,097,369","19,341,327","19,584,927","19,897,747","20,268,567","20,656,589","20,984,400"
10,Georgia,"9,687,653","9,688,690","9,712,696","9,810,595","9,911,171","9,981,773","10,083,850","10,199,533","10,313,620","10,429,379"
11,Hawaii,"1,360,301","1,360,301","1,363,817","1,378,323","1,392,772","1,408,038","1,417,710","1,426,320","1,428,683","1,427,538"
12,Idaho,"1,567,582","1,567,650","1,570,912","1,583,180","1,594,673","1,610,187","1,630,391","1,649,324","1,680,026","1,716,943"
13,Illinois,"12,830,632","12,831,565","12,841,196","12,862,298","12,878,494","12,890,403","12,882,438","12,862,051","12,835,726","12,802,023"
14,Indiana,"6,483,802","6,484,125","6,490,029","6,515,358","6,535,665","6,567,484","6,593,182","6,610,596","6,634,007","6,666,818"
15,Iowa,"3,046,355","3,046,869","3,050,223","3,063,690","3,074,386","3,089,876","3,105,563","3,118,473","3,130,869","3,145,711"
16,Kansas,"2,853,118","2,853,130","2,858,403","2,868,756","2,885,316","2,892,900","2,899,553","2,905,789","2,907,731","2,913,123"
17,Kentucky,"4,339,367","4,339,340","4,347,948","4,368,505","4,383,673","4,399,121","4,410,415","4,422,057","4,436,113","4,454,189"
18,Louisiana,"4,533,372","4,533,478","4,544,871","4,574,388","4,602,681","4,626,795","4,648,797","4,671,211","4,686,157","4,684,333"
19,Maine,"1,328,361","1,328,362","1,327,568","1,327,968","1,328,101","1,327,975","1,328,903","1,327,787","1,330,232","1,335,907"
20,Maryland,"5,773,552","5,773,807","5,788,099","5,843,115","5,891,680","5,932,654","5,970,245","6,000,561","6,024,752","6,052,177"
21,Massachusetts,"6,547,629","6,547,808","6,564,943","6,612,178","6,659,627","6,711,138","6,757,925","6,794,002","6,823,721","6,859,819"
22,Michigan,"9,883,640","9,884,129","9,876,731","9,876,199","9,886,610","9,899,219","9,914,675","9,918,170","9,933,445","9,962,311"
23,Minnesota,"5,303,925","5,303,924","5,310,711","5,345,967","5,377,695","5,416,074","5,452,649","5,483,238","5,525,050","5,576,606"
24,Mississippi,"2,967,297","2,968,103","2,970,437","2,977,452","2,982,963","2,987,721","2,988,578","2,985,297","2,985,415","2,984,100"
25,Missouri,"5,988,927","5,988,925","5,995,681","6,010,280","6,023,267","6,041,142","6,058,014","6,072,640","6,091,176","6,113,532"
26,Montana,"989,415","989,414","990,507","996,866","1,003,522","1,011,921","1,019,931","1,028,317","1,038,656","1,050,493"
27,Nebraska,"1,826,341","1,826,327","1,829,956","1,841,641","1,854,862","1,867,414","1,880,920","1,893,564","1,907,603","1,920,076"
28,Nevada,"2,700,551","2,700,691","2,702,797","2,718,170","2,752,410","2,786,547","2,831,730","2,883,057","2,939,254","2,998,039"
29,New Hampshire,"1,316,470","1,316,460","1,316,700","1,318,345","1,320,923","1,322,622","1,328,684","1,330,134","1,335,015","1,342,795"
30,New Jersey,"8,791,894","8,791,953","8,803,708","8,844,694","8,882,095","8,913,735","8,943,010","8,960,001","8,978,416","9,005,644"
31,New Mexico,"2,059,179","2,059,207","2,064,607","2,077,744","2,083,590","2,085,161","2,083,207","2,082,264","2,085,432","2,088,070"
32,New York,"19,378,102","19,378,110","19,405,185","19,526,372","19,625,409","19,712,514","19,773,580","19,819,347","19,836,286","19,849,399"
33,North Carolina,"9,535,483","9,535,721","9,574,247","9,662,940","9,755,299","9,849,812","9,941,160","10,041,769","10,156,689","10,273,419"
34,North Dakota,"672,591","672,585","674,518","684,830","701,380","722,908","738,658","754,859","755,548","755,393"
35,Ohio,"11,536,504","11,536,730","11,539,282","11,543,332","11,546,969","11,567,845","11,593,741","11,606,027","11,622,554","11,658,609"
36,Oklahoma,"3,751,351","3,751,598","3,759,529","3,785,232","3,815,298","3,849,840","3,875,008","3,904,353","3,921,207","3,930,864"
37,Oregon,"3,831,074","3,831,072","3,837,073","3,865,845","3,893,920","3,919,664","3,960,673","4,016,537","4,085,989","4,142,776"
38,Pennsylvania,"12,702,379","12,702,857","12,711,063","12,742,811","12,768,034","12,778,450","12,790,341","12,791,124","12,787,085","12,805,537"
39,Rhode Island,"1,052,567","1,052,945","1,053,169","1,052,154","1,052,761","1,052,784","1,054,782","1,055,916","1,057,566","1,059,639"
40,South Carolina,"4,625,364","4,625,381","4,635,834","4,672,744","4,719,009","4,765,862","4,824,758","4,892,423","4,959,822","5,024,369"
41,South Dakota,"814,180","814,197","816,227","823,338","832,576","842,513","849,455","854,036","861,542","869,666"
42,Tennessee,"6,346,105","6,346,295","6,355,882","6,396,281","6,450,632","6,490,795","6,540,007","6,590,726","6,649,404","6,715,984"
43,Texas,"25,145,561","25,146,100","25,241,648","25,644,424","26,078,327","26,479,279","26,954,436","27,454,880","27,904,862","28,304,596"
44,Utah,"2,763,885","2,763,889","2,775,260","2,815,430","2,854,222","2,899,961","2,938,671","2,984,917","3,044,321","3,101,833"
45,Vermont,"625,741","625,741","625,842","626,210","625,606","626,044","625,665","624,455","623,354","623,657"
46,Virginia,"8,001,024","8,001,043","8,025,206","8,107,548","8,188,656","8,261,689","8,316,902","8,366,767","8,414,380","8,470,020"
47,Washington,"6,724,540","6,724,545","6,741,386","6,819,155","6,890,899","6,963,410","7,046,931","7,152,818","7,280,934","7,405,743"
48,West Virginia,"1,852,994","1,853,006","1,854,315","1,854,891","1,855,360","1,852,333","1,847,624","1,839,767","1,828,637","1,815,857"
49,Wisconsin,"5,686,986","5,687,288","5,690,403","5,705,812","5,721,075","5,736,673","5,751,272","5,759,744","5,772,917","5,795,483"
50,Wyoming,"563,626","563,767","564,376","567,602","576,608","582,341","583,334","586,102","584,910","579,315"